### ISSUE TITLE
Server crash due NBT data 

### ISSUE THREAD

**Issue by NLBlacky** [Ivorforce/RecurrentComplex#363] opened 2018-12-29 19:24 UTC
So apparently our server is crashing because the loot inside the Recurrent Complex bigger structures has a too large NBT tag. Here is one of the crashlogs: [Crashlog NBT](https://pastebin.com/ueBMr7fr)

How can I solve this? Or maybe modify the loot?

Our server had issues with this mod before as the larger structures freeze/crash our server. We managed to solve this by decreasing the timeout to 50 ms. We however have not been able to fix this issue yet.

**Comment by Ivorforce** [comment] 2019-03-11 22:36
I think this is actually caused by cascading chunk gen (and maze solving), and it just happens to crash on NBT load. Decreasing structureSpawnChance, tree decoration replacement chance and maze timeout are good ways to circumvent it for now.

Either way - Duplicate of #155. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 22:36 UTC
