### ISSUE TITLE
[Server thread/WARN]

### ISSUE THREAD

**Issue by RealSenZ0** [Ivorforce/RecurrentComplex#369] opened 2019-02-01 14:46 UTC
[14:45:27] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [14, 12] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:27] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [14, 13] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:27] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [13, 14] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:27] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [14, 14] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:28] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [0, 1] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:28] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:29] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [0, 3] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:29] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:30] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [0, 2] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:30] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:30] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [1, 2] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:30] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:30] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [2, 3] in dimension 0 (overworld) while populating chunk [1, 2], causing cascading worldgen lag.
[14:45:30] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:30] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [2, 2] in dimension 0 (overworld) while populating chunk [1, 2], causing cascading worldgen lag.
[14:45:30] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:30] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [1, 1] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.
[14:45:30] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:45:31] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [1, 0] in dimension 0 (overworld) while populating chunk [13, 13], causing cascading worldgen lag.

Dude, it's everywhere!!!

**Comment by Ivorforce** [comment] 2019-03-11 22:18
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now.

**Closed by Ivorforce** 2019-03-11 22:18 UTC
