### ISSUE TITLE
Worldgen lag

### ISSUE THREAD

**Issue by StellarHarbour** [Ivorforce/RecurrentComplex#499] opened 2023-10-19 09:53 UTC
Please report this to the mod's issue tracker.
Recurrent Complex loaded a new chunk [15, -18] in dimension 0 (overworld) while populating chunk [16, -19], causing cascading worldgen lag.

**Comment by gwynhefar** [comment] 2024-03-15 04:32
I have the same issue: 


[00:22:55] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [39, 8] in dimension 0 (overworld) while populating chunk [38, 7], causing cascading worldgen lag.
00:22:55.942
game
[00:22:55] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
00:22:56.010
game
[00:22:56] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [39, 7] in dimension 0 (overworld) while populating chunk [38, 7], causing cascading worldgen lag.
00:22:56.010
game
[00:22:56] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
00:22:57.214
game
[00:22:57] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3004ms behind, skipping 60 tick(s)

**Comment by Ivorforce** [comment] 2024-08-06 10:09
Duplicate of #155

**Closed by Ivorforce** 2024-08-06 10:09 UTC
