### ISSUE TITLE
[1.12.2] Crash when right clicking loot components on regular blocks

### ISSUE THREAD

**Issue by Alan19** [Ivorforce/RecurrentComplex#324] opened 2018-05-10 16:58 UTC
When I right click the loot components (the white circle ones) while I am facing a block, the game crashes. This does not occur when I right click on blocks like doors and chest, but does occur on decorative blocks as well as natural air.

https://paste.dimdev.org/evulasibiv.txt

**Comment by Ivorforce** [comment] 2019-03-17 19:26
Ah, duplicate of #iforgethonestly. But it's been fixed already.

**Closed by Ivorforce** 2019-03-17 19:26 UTC
