### ISSUE TITLE
Structures Sliced Bug

### ISSUE THREAD

**Issue by Lt1489** [Ivorforce/RecurrentComplex#242] opened 2017-06-28 01:14 UTC
Minecraft 1.11.2
Forge-13.20.0.2366
IvToolkit-1.3.3
RecurrentComplex-1.4.1

This only happens sometimes
![Sliced Structure](http://i.imgur.com/uUwP7QP.jpg)
It's also aligns to other RecurrentComplex structures
![Sliced Structure](http://i.imgur.com/rselJoz.jpg)
If more info is needed, I'll be happy to provide it.

**Comment by QuImUfu** [comment] 2017-06-28 01:53
Duplicate of #222 , is already fixed, wait for a new version release.

**Closed** 2017-06-28 02:01 UTC
