### ISSUE TITLE
1.10 crash during chunk generation

### ISSUE THREAD

**Issue by bogger33** [Ivorforce/RecurrentComplex#230] opened 2017-06-19 17:14 UTC
https://gist.github.com/bogger33/0cd6120420a754baaefec31c614a7660

Using speigers chunk pre-generator to generate chunks on my server, and occasionally recurrent complex will crash.

**Comment by kwpugh** [comment] 2017-06-20 00:14
I'm getting the same issue with my 1.11.2 server

https://gist.github.com/kwpugh/5fd6cf96531bfa5deff147c961a2a7b6

**Comment by Ivorforce** [comment] 2017-06-20 20:13
Duplicate of #223.

**Closed by Ivorforce** 2017-06-20 20:13 UTC
