### ISSUE TITLE
1.11.2 Cascading worldgen lag

### ISSUE THREAD

**Issue by GeebsRilie** [Ivorforce/RecurrentComplex#190] opened 2017-05-03 07:11 UTC
I keep getting this message while the world doesnt load.

> [00:05:05] [Server thread/WARN]: Recurrent Complex loaded a new chunk (-34, 7  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [00:05:06] [Server thread/WARN]: Recurrent Complex loaded a new chunk (-33, 30  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [00:05:07] [Server thread/WARN]: Recurrent Complex loaded a new chunk (-30, 32  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [00:05:09] [Server thread/WARN]: Recurrent Complex loaded a new chunk (-31, 33  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
>

**Comment by Ivorforce** [comment] 2017-05-04 15:36
Duplicate of #155

**Closed by Ivorforce** 2017-05-04 15:36 UTC
Labels: duplicate
