### ISSUE TITLE
Crash with Biomes O Plenty when exploring

### ISSUE THREAD

**Issue by Kehaan** [Ivorforce/RecurrentComplex#193] opened 2017-05-06 11:11 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.5.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.5.27.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/6/17 1:10 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:stonebrick, properties=[variant]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:287)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerRuins.transform(TransformerRuins.java:209)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerRuins.transform(TransformerRuins.java:57)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti.lambda$transform$55(TransformerMulti.java:182)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti$$Lambda$1107/867657265.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti.transform(TransformerMulti.java:182)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:259)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:145)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.generateStructureInChunk(WorldGenStructures.java:116)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$generateRandomStructuresInChunk$687(WorldGenStructures.java:74)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures$$Lambda$1032/1902933435.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.generateRandomStructuresInChunk(WorldGenStructures.java:74)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:187)
	at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_397_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:482)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:287)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerRuins.transform(TransformerRuins.java:209)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerRuins.transform(TransformerRuins.java:57)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti.lambda$transform$55(TransformerMulti.java:182)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti$$Lambda$1107/867657265.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at ivorius.reccomplex.world.gen.feature.structure.generic.transformers.TransformerMulti.transform(TransformerMulti.java:182)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:259)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:145)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.generateStructureInChunk(WorldGenStructures.java:116)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$generateRandomStructuresInChunk$687(WorldGenStructures.java:74)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures$$Lambda$1032/1902933435.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.generateRandomStructuresInChunk(WorldGenStructures.java:74)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:187)
	at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_397_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:482)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['kehaan'/330, l='New World', x=1317.53, y=75.11, z=3746.67]]
	Chunk stats: ServerChunkCache: 821 Drop: 0
	Level seed: -581080662195627824
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-52,64,308), Chunk: (at 12,4,4 in -4,19; contains blocks -64,0,304 to -49,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6252 game time, 11953 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1078231840 bytes (1028 MB) / 2600992768 bytes (2480 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	additionalresources{0.1.1} [Additional Resources] (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	AppleCore{2.1.2} [AppleCore] (AppleCore-mc1.10.2-2.1.2.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJAAAA	audiodeath{0.6.3_1.9-1311200} [Audio Death] (audiodeath-1.9-0.6.3.47+1311200.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJAAAA	Baubles{1.3.10} [Baubles] (Baubles-1.10.2-1.3.10.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.6.jar) 
	UCHIJAAAA	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.5.jar) 
	UCHIJAAAA	betterthanbunnies{1.10.2-1.1.0} [BetterThanBunnies] (BetterThanBunnies-1.10.2-1.1.0.jar) 
	UCHIJAAAA	bettertitlescreen{1.2e} [Better Title Screen] (BetterTitleScreen-1.10.2-1.2e.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	buttons{1.10.2-0.0.3-3} [Buttons] (Buttons-1.10.2-0.0.3-3.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	chancecubes{1.10.2-2.3.6.176} [Chance Cubes] (ChanceCubes-1.10.2-2.3.6.176.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJAAAA	cyclicmagic{1.10.22} [Cyclic] (Cyclic-1.10.2-1.10.22.jar) 
	UCHIJAAAA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJAAAA	deathquotes{1.2.0} [Death Quotes] (DeathQuotes-1.2.0-mc1.9to1.10.2-forge.jar) 
	UCHIJAAAA	eiramoticons{4.2.4} [EiraMoticons] (EiraMoticons_1.10.2-4.2.4.jar) 
	UCHIJAAAA	enchiridion{3.1.17} [Enchiridion] (Enchiridion-1.10.2-3.1.17.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-anarchy.jar) 
	UCHIJAAAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
	UCHIJAAAA	googlyeyes{6.0.0} [GooglyEyes] (GooglyEyes-1.10.2-6.0.0.jar) 
	UCHIJAAAA	hardcorewither{2.2.3} [Hardcore Wither] (hardcoreWither-1.10.2-2.2.3-beta-4bd2a01-universal.jar) 
	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJAAAA	harvestfestival{0.5.27} [Harvest Festival] (Harvest-Festival-1.10.2-0.5.27.jar) 
	UCHIJAAAA	Waila{1.8.13-B27_1.10.2} [Waila] (Hwyla-1.8.13-B27_1.10.2.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.2.jar) 
	UCHIJAAAA	initialinventory{1.0.1} [InitialInventory] (InitialInventory-1.0.1.jar) 
	UCHIJAAAA	InventoryPets{1.4.9.4} [Inventory Pets] (inventorypets-1.10-1.4.9.4.jar) 
	UCHIJAAAA	inventorysorter{0.11.0+47} [Simple Inventory sorting] (inventorysorter-1.10.2-0.11.0+47.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	levels{r1.2.8} [Levels] (Levels 2-1.10.2-r1.2.8.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	mob_properties{1.0.3} [Mob Properties] (mob_properties-1.10.2-1.0.3.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.55} [Natura] (natura-1.10.2-4.1.0.55.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	railcraft{10.1.1} [Railcraft] (Railcraft_1.10.2-10.1.1.jar) 
	UCHIJAAAA	reccomplex{1.3-1.10} [Recurrent Complex] (RecurrentComplex-1.3-1.10.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.3} [Storage Drawers] (StorageDrawers-1.10.2-3.7.3.jar) 
	UCHIJAAAA	refinedstorage{1.2.25} [Refined Storage] (refinedstorage-1.2.25.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	SimpleAchievements{MC1.9.4-1.2.2-28} [Simple Achievements] (SimpleAchievements-MC1.9.4-1.2.2-28.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.8.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCHIJAAAA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.3.1.2.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar)
  
HFTransformer (Harvest-Festival-1.10.2-0.5.27.jar)
  joshie.harvest.asm.HFTransformer
IvToolkit (IvToolkit-1.3.3-1.10.jar)
  
AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['kehaan'/330, l='New World', x=1317.53, y=75.11, z=3746.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BrisingrAerowing** [comment] 2017-05-06 14:59
Duplicate of #191

**Closed** 2017-05-06 23:27 UTC
Labels: duplicate
