### ISSUE TITLE
WorldGen probs?

### ISSUE THREAD

**Issue by Nexusdog** [Ivorforce/RecurrentComplex#322] opened 2018-04-05 10:17 UTC
Going through latest log, I came across this

 [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (-13, 10  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. 
 [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (-13, 25  Dimension: 0) during chunk population, causing cascading worldgen lag.
[Server thread/WARN] [reccomplex]: Cascading chunk generation happening while preparing VillageTriplets
Recurrent Complex loaded a new chunk (-12, 7  Dimension: 0)...

Also;

[Server thread/WARN] [reccomplex]: Cascading chunk generation happening while placing CuboneSkull

Think there was also one mentioning the pokemon trainer in there somewhere. 

And so on.

So far, other mods having similar warnings are Ore Shrubs, Actually Additions and Gravestone Extended (though not to the extent as RC), from what I can see.

**Comment by codetaylor** [comment] 2018-04-13 20:17
Found the same issue, here is the relevant bit from my log along with the full log:

Snip: https://gist.github.com/codetaylor/bc013248810b78075b20c0eaa6ef793c
Full: https://gist.github.com/codetaylor/e7e519af3ba8209a6a9be39f19759c38

**Comment by BrisingrAerowing** [comment] 2018-04-18 22:34
I'm getting this as well. It causes major lag lasting up to 2 minutes, as well as a memory usage spike. I ended up hitting an OOM situation with it as well (I have 10 GB allocated and usually hover around 8 GB used).

**Comment by jusitnboggs** [comment] 2018-05-31 04:45
Same here too

**Comment by seebs** [comment] 2018-08-22 17:13
A bit of research confirms that this message is not spurious, it is actually genuinely triggering cascading worldgen, especially if it happens to hit any other mods that do worldgen. But RC is the only one producing the diagnostic, so I think it's doing something different from wthat they're doing.

**Comment by Ivorforce** [comment] 2019-03-11 22:31
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 22:31 UTC
