### ISSUE TITLE
property integer

### ISSUE THREAD

**Issue by yggdrasil75** [Ivorforce/RecurrentComplex#196] opened 2017-05-07 19:53 UTC
I dont know what the error in this actually is caused by, it occured during world creation, and the only thing I recognize as a possible error is clazz=class this sounds a bit weird. the rest is in this [log](https://gist.github.com/yggdrasil75/c8b4cafa9427e5521f4be5459d18f0f1)

**Comment by Ivorforce** [comment] 2017-05-07 19:54
Duplicate of #191. Already fixed, will be part of the next version.

**Closed by Ivorforce** 2017-05-07 19:54 UTC
