### ISSUE TITLE
Server crashing, possibly due to cascading worldgen lag (ServerHangWatchdog detected that a single server tick took 60.00 seconds)

### ISSUE THREAD

**Issue by CocaineJohnsson** [Ivorforce/RecurrentComplex#372] opened 2019-03-06 11:21 UTC
The cascading worldgen lag gets particularly nasty at times, causing the server to lag behind by seconds (second highest over 19,000ms) - this ought not to be an io throughput or cpu availability issue as it's hosted on an 8 core ryzen 7 build and stored on a decently fast SSD.

At peak it crashes my server (reliably for the same village in the same seed) 

The crash log points a finger at the ivorius.reccomplex namespace, bug report here: https://zerobin.net/?0d9b9e02d46956e8#4OW5n16f4zVGhjEJ85/gn3XqUA/HQjNnfSFiYK6s4/o=

I elected to post it as a paste for sake of readability, but if requested I can instead embed it here as a code block.

**Comment by CocaineJohnsson** [comment] 2019-03-06 11:31
Almost certainly the best fix is to see how minecraft itself handles cross-chunk structures (e.g mineshafts, strongholds, fortresses) - these are located in iirc the net.minecraft.world.gen.structure namespace.

**Comment by Ivorforce** [comment] 2019-03-11 22:18
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now.

**Closed by Ivorforce** 2019-03-11 22:18 UTC
