### ISSUE TITLE
Random crash relating to the book generator

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#228] opened 2017-06-18 19:47 UTC
https://pastebin.com/keknAa93

But I haven't even touched it on 1.11.2...

**Comment by bogger33** [comment] 2017-06-19 16:25
I got this too

**Comment by Ivorforce** [comment] 2017-06-20 20:11
Duplicate of #227.

**Closed by Ivorforce** 2017-06-20 20:11 UTC

**Comment by Sunconure11** [comment] 2017-06-21 00:56
Issue happens for me on 1.11.2, any plans to bring the fix over there?

**Comment by Ivorforce** [comment] 2017-06-21 14:30
Did I enter it wrong in curse? The releases are for 1.11 and 1.10

Am 21.06.2017 02:56 schrieb "Anonymous" <notifications@github.com>:

**Comment by Sunconure11** [comment] 2017-06-21 17:30
I see releases for 1.12 and 1.10. I think you did.
