### ISSUE TITLE
Crash , forge 1388

### ISSUE THREAD

**Issue by Pilad** [Ivorforce/RecurrentComplex#20] opened 2015-04-29 05:39 UTC
Crash log
http://pastebin.com/7akAuKxu

**Comment by Ivorforce** [comment] 2015-04-29 08:57
Duplicate of #16 - in short, please do not use the 10.13.3.1388 build or later for now. They know about it, have fixed it, but haven't made a new build yet...

**Closed by Ivorforce** 2015-04-29 08:57 UTC
Labels: duplicate
