### ISSUE TITLE
Crash with blank space in install path

### ISSUE THREAD

**Issue by Mattsingen** [Ivorforce/RecurrentComplex#14] opened 2015-03-30 10:19 UTC
We got the crash log below as a support ticket for the resonant rise pack. I'm not a java programmer, so I can only guess, but I think that the code might lack some quotation marks on the path string.

http://pastebin.com/2cffwz6B

**Comment by Ivorforce** [comment] 2015-03-30 10:25
This is a duplicate of #5 - in short, it's a Windows JDK bug I can do little about. Apparently it's been fixed in Java 8, so it might help to update. If that doesn't help, I can only recommend to install it in a path where there are no spaces.

**Closed by Ivorforce** 2015-03-30 10:25 UTC

**Comment by Mattsingen** [comment] 2015-03-30 14:35
Thanks for the quick response and sorry for the duplicate...
