### ISSUE TITLE
Crashing on Server

### ISSUE THREAD

**Issue by RenanVieira88** [Ivorforce/RecurrentComplex#367] opened 2019-01-24 00:38 UTC
https://pastebin.com/PJntrvmw

Seens like something with BOP

**Comment by Ivorforce** [comment] 2019-03-11 22:19
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now.

**Closed by Ivorforce** 2019-03-11 22:19 UTC
