### ISSUE TITLE
Vanilla rails and rotation

### ISSUE THREAD

**Issue by Thutmose** [Ivorforce/RecurrentComplex#27] opened 2015-08-22 22:47 UTC
Vanilla rails do not rotate correctly

![image](https://cloud.githubusercontent.com/assets/2363472/9426185/44014998-48fe-11e5-9ad1-c25953efce48.png)

this pattern when rotated gives 

![image](https://cloud.githubusercontent.com/assets/2363472/9426182/320283a6-48fe-11e5-83ae-c07d2cb8389d.png)

**Comment by Ivorforce** [comment] 2015-09-01 17:09
I'm guessing this is either a Forge bug in the rotation code, or an inherent problem with onPlace updates. I'll keep this open for future investigation, but it's likely I won't be able to do much about it myself.

**Comment by Ivorforce** [comment] 2015-09-06 16:42
Update: Yep, pretty sure it's a Forge bug. Even rotating single rails is not at all accurate. I'll note this down to maybe PR to Forge, but it's not a bug relevant to ReC, so I'm closing this issue.

**Closed by Ivorforce** 2015-09-06 16:42 UTC
