### ISSUE TITLE
Apply templates on exporting Crash

### ISSUE THREAD

**Issue by CcytherR** [Ivorforce/RecurrentComplex#36] opened 2015-11-03 17:37 UTC
Crash when exporting structure just made out of vanilla blocks custom birch tree after changing biomes i was seeing what apply presets does and when i clicked it did something then crashed with this error http://pastebin.com/5yZXPX9R Seems it isnt repeatable maybe it was a one off

**Comment by Ivorforce** [comment] 2016-03-09 20:40
I think this was fixed in f9104382fed1a7238fc5c170e2363fd097561d93 (and possibly one of the earlier commits). It was caused by using the mouse wheel to scroll.

But just in case, if it was not please do reopen the issue.

**Closed by Ivorforce** 2016-03-09 20:40 UTC
