### ISSUE TITLE
[1.12.2] Cascading Chunk Generation

### ISSUE THREAD

**Issue by DatsiK96** [Ivorforce/RecurrentComplex#312] opened 2018-02-24 03:42 UTC
[19:24:53] [Server thread/WARN] [reccomplex]: Cascading chunk generation happening while pre-complementing NetherThorn1
[19:24:53] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (0, 0  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:05:52] [Server thread/WARN] [reccomplex]: Cascading chunk generation happening while placing NetherThorn3
[19:05:52] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (-12, -12  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:06:02] [Server thread/WARN] [reccomplex]: Cascading chunk generation happening while placing NetherThorn1
[19:06:02] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (-7, -16  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[19:06:04] [Server thread/WARN] [reccomplex]: Cascading chunk generation happening while generating NetherThorn1
[19:06:04] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (0, 0  Dimension: -1) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Getting this warning quite often. It's happening in the Nether as I move around generating new chunks.

I have the latest version as of 2/20/2018 of Recurrent Complex

**Comment by Ivorforce** [comment] 2019-03-11 23:04
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 23:04 UTC
