### ISSUE TITLE
NPE when trying to toy with a loot template

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#332] opened 2018-06-11 06:09 UTC
https://paste.dimdev.org/kunazukiba.mccrash

**Comment by Ivorforce** [comment] 2019-03-11 23:01
Duplicate of #338. Technically you were first, but I commented the other one already lol. I should be able to make a quick fix for this in the next update.

**Closed by Ivorforce** 2019-03-11 23:01 UTC
