### ISSUE TITLE
Add bounding box check for structure-terrain suitability

### ISSUE THREAD

**Issue by MagusLucius** [Ivorforce/RecurrentComplex#327] opened 2018-05-22 04:08 UTC
I've seen the serpent temple spawn half-inside a mountain with part of the peak sticking out above it, and the meteor crater spawned halfway out over a river gorge.

I'm not sure how, or if, this could be fixed, but I thought I'd report it.

Minecraft 1.12.2
forge-1.12.2-14.23.3.2655
RecurrentComplex-1.4.7

other mods of interest: GeographiCraft-1.12.2-0.8.9b

**Comment by chland** [comment] 2018-06-11 09:49
Duplicate of https://github.com/Ivorforce/RecurrentComplex/issues/218

**Comment by Ivorforce** [comment] 2019-03-11 23:12
Yep, duplicate. There _are_ a bunch of systems in place to avoid this problem, but it seems they fail at times still.

**Closed by Ivorforce** 2019-03-11 23:12 UTC
