### ISSUE TITLE
[1.10.2/Mod 1.2.10] Structures spawn partially in villages

### ISSUE THREAD

**Issue by MadByteDE** [Ivorforce/RecurrentComplex#179] opened 2017-04-21 08:26 UTC
I've seen this problem a lot recently. 
Settings are default.

![Image 1](http://i.imgur.com/r9lLu8M.png)
![Image 2](http://i.imgur.com/iWTZBQa.png)

Even more stuff (Building inside a building etc)
Album: (http://imgur.com/a/a435I)

**Comment by Ivorforce** [comment] 2017-04-21 15:44
Duplicate of #51

**Closed by Ivorforce** 2017-04-21 15:44 UTC
