### ISSUE TITLE
[1.11.2 - 1.2.10] cascading worldgen lag crash

### ISSUE THREAD

**Issue by Boodaflow** [Ivorforce/RecurrentComplex#185] opened 2017-04-29 22:07 UTC
After starting up a new world, I started exploring near the spawn point until a sudden crash.
This issue seems to involve several mods including: Embers, Inventory Pets, AbyssalCraft, Recurrent Complex, Astral Sorcery, denseores, and Roguelike Dungeons.

[15:09:10] [Server thread/WARN]: Recurrent Complex loaded a new chunk (-23, 23  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I tried posting the log in zip, but it wouldn't upload.

**Comment by Boodaflow** [comment] 2017-05-01 21:47
capnkirok of Inventory-Pets seems to have the solution:

https://github.com/capnkirok/Inventory-Pets/issues/170

**Comment by Ivorforce** [comment] 2017-05-04 15:40
Duplicate of #155.
Their fix will not work for ReC. The main issue is big structures rather than their shift - I have started work on fixing the issue but it will take a little while longer.

**Closed by Ivorforce** 2017-05-04 15:40 UTC
Labels: duplicate
