### ISSUE TITLE
Excessive amount of Dead Trees in every biome that has trees!

### ISSUE THREAD

**Issue by SirAron111** [Ivorforce/RecurrentComplex#355] opened 2018-10-22 15:06 UTC
Excessive amount of Dead Trees in every biome that has trees!
Nearly every 3 chunks there is one thats to many what s going on even tried instaling only the mod and nothing else still so many?
Forgeversion: 14.23.5.2768

**Comment by Lodugh** [comment] 2018-11-02 14:06
Duplicate of #333

**Comment by Ivorforce** [comment] 2019-03-11 22:44
Yup, duplicate.

**Closed by Ivorforce** 2019-03-11 22:44 UTC
