### ISSUE TITLE
A loop of server warn log and caused all players timed out

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Ivorforce/RecurrentComplex#337] opened 2018-07-13 11:35 UTC
[19:26:25] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [11, 1] in dimension 7 (twilight_forest) while populating chunk [11, 0], causing cascading worldgen lag.
[19:26:25] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by Ivorforce** [comment] 2019-03-11 22:30
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 22:30 UTC

**Comment by Pythonic-Rainbow** [comment] 2019-04-03 09:34
@Ivorforce thanks for the reply, how can we reduce tree decoration replacement chance?

**Comment by Ivorforce** [comment] 2019-04-03 10:20
It's an option in the config called baseWeight_tree

**Comment by Pythonic-Rainbow** [comment] 2019-04-07 08:37
Ok thanks.
