### ISSUE TITLE
[1.10.2] Client crash when generating maze

### ISSUE THREAD

**Issue by ruyanve** [Ivorforce/RecurrentComplex#85] opened 2016-09-10 22:48 UTC
Updated to 1.0.3 and crashed after running a couple of minutes... Used to work fine with RecurrentComplex-1.0.2.jar in combination with RTG
https://gist.github.com/ruyanve/d2720fd0b2c1fcd5f856d954ad8f01a1

**Comment by Ivorforce** [comment] 2016-09-10 23:21
Is that a custom structure / maze? I can't reproduce the issue with either stone or forest mazes.

**Comment by Ivorforce** [comment] 2016-09-10 23:37
Nevermind, I just got it. Working on resolving the issue.

**Comment by Ivorforce** [comment] 2016-09-10 23:42
Fixed in the latest IvToolkit nightly.

**Closed by Ivorforce** 2016-09-10 23:42 UTC
