### ISSUE TITLE
[1.12][v1.4.3] Fatal errors during world load

### ISSUE THREAD

**Issue by starg09** [Ivorforce/RecurrentComplex#245] opened 2017-06-29 15:36 UTC
Client stucks at the "Building Terrain" screen, and the launcher log [outputs this error](https://gist.github.com/starg09/1620e786d0b3cfb147630512e2d17d5f) (only appears on the event log, not on the log file). Only thing that can be done at that point is force-kill the java process.

Versions used:

* MC 1.12
* Forge 2387 (RB)
* IvToolkit 1.3.3
* RecComplex 1.4.3

**Comment by starg09** [comment] 2017-06-29 15:39
(Updated the gist to one with only IVToolkit and RecComplex, since it seems to happen even with the two them alone)

**Comment by Ivorforce** [comment] 2017-06-29 18:35
Duplicate of #224.

**Closed by Ivorforce** 2017-06-29 18:35 UTC

**Comment by starg09** [comment] 2017-06-29 18:36
Ahh, took a bit to submit and didn't notice that one... Sorry! :P

**Comment by Ivorforce** [comment] 2017-06-29 18:37
No problem, I'm glad it gets reported in the first place :)
