### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by C0rn3j** [Ivorforce/RecurrentComplex#92] opened 2016-09-28 18:41 UTC
When arriving at this structure my server console went crazy with errors.

http://i.imgur.com/XgUZkYt.jpg

http://pastebin.com/y7yVxjKa - looks to be this error over and over again

**Comment by Ivorforce** [comment] 2016-10-02 13:45
Is there any way to reproduce the issue? I tested the structure but it works fine. I also checked the code but the error seems somehow impossible... Maybe update Forge?

**Comment by C0rn3j** [comment] 2016-10-04 19:25
Well Forge was version 2092(2094 was newest at the time). I guess I could give you the world seed and you can see if it happens on it?

**Comment by Ivorforce** [comment] 2016-10-04 22:44
I have found the place, but my structure registry seems to be different from yours - in the place where you got the fort, it generates a spider pit for me. Do you have some mod that modifies vanilla loot tables?

**Comment by C0rn3j** [comment] 2016-10-04 22:48
https://wiki.c0rn3j.com/index.php?title=Minecraft#Modlist

**Comment by Ivorforce** [comment] 2016-10-04 22:52
I don't know those mods well enough to warrant a judgement on that myself :P 
But I'm currently guessing that must be it. Like I said, from a code perspective, that problem seems to be impossible, so it must be a coremod change of sorts bringing it out. Although it seems weird that it won't happen in villages too, then.

I'll leave this issue open for now but unless there's more info somewhere (e.g. I can reproduce it or it turns out to be some other mod) I don't see a way to tackle it currently.

**Comment by C0rn3j** [comment] 2016-10-04 22:52
There's a download link to all these mods if you want to test it yourself. It should work fine if you downgrade Baubles to a stable version.

**Comment by C0rn3j** [comment] 2016-10-04 23:11
Btw it might possibly be Enchanting plus, I already reported a bug to LootBags and it turned out to be a problem with loot tables caused by EP.

https://minecraft.curseforge.com/projects/enchanting-plus

**Comment by InsomniaKitten** [comment] 2016-10-05 14:31
Ivorforce, the structure generation you got from that seed is likely different because C0rn3j appears to be using Biomes O' Plenty when generating their world. Just thought I should point that out

**Comment by Ivorforce** [comment] 2016-10-06 23:19
Closing this since @darkhax has confirmed it to be caused by Enchanting Plus.

**Closed by Ivorforce** 2016-10-06 23:19 UTC
