### ISSUE TITLE
Causes cascading lag

### ISSUE THREAD

**Issue by ChaoticLogic** [Ivorforce/RecurrentComplex#350] opened 2018-09-21 15:56 UTC
While playing in single player, I noticed I was getting block lag. I've never experienced this in SP, just when playing on a server.  The log contained this:

[09:09:19] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [33, -41] in dimension 0 (overworld) while populating chunk [34, -41], causing cascading worldgen lag.

This message repeats between 12-20 times listing sequential chunk numbers.

**Comment by WailordUBS** [comment] 2018-09-22 22:31
I got the same thing on my multiplayer server
[crash-2018-09-22_17.28.51-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/2408227/crash-2018-09-22_17.28.51-server.txt)
:

**Comment by lordfriend** [comment] 2018-09-28 12:20
I encounter the same issue causing my server stopped...

[crash-2018-09-25_13.02.36-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/2428115/crash-2018-09-25_13.02.36-server.txt)

**Comment by cyberpwnn** [comment] 2018-10-30 09:20
Its like playing minesweeper! Never know when you are going to get lucky! https://hastebin.com/izisejidil.md Turns out luck isnt usually on my side.

**Comment by Dorfinger** [comment] 2018-12-28 18:34
Still causing issues in 1.47.

**Comment by P3rf3ctXZer0** [comment] 2019-01-11 04:09
[22:05:47] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [224, 2] in dimension 0 (overworld) while populating chunk [223, 2], causing cascading worldgen lag.
[22:05:47] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by Ivorforce** [comment] 2019-03-11 22:27
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 22:27 UTC
