### ISSUE TITLE
Crashing on spawn generation

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [Ivorforce/RecurrentComplex#38] opened 2015-11-18 08:59 UTC
Hi!

I'm using nigtly build of recurrent complex and ivtoolkit n139 and n85, forge is at latest recomended for 1.7.10, I created a spawn structure using reinforced blocks by open modular turrets mod, a garage door by malissis doors and some basic turrets (from open modular turrets). I've set to "spawn" the structure at spawn with a Y shift of 80 because it has a deep dungeon underneath, here is the crash:

http://pastebin.com/MfWrAvkX

I'm going to spawn a small build made with vanilla blocks and without y shift to be sure if the building blocks are the problem.

Thank you so much for your time.

**Comment by Merancapeman** [comment] 2016-03-01 03:29
Would have been nice to get some feedback on this.

**Comment by Ivorforce** [comment] 2016-03-01 09:16
I'm going to have a look at it for the next release. I haven't been able to work on ReC in quite a while, but I should be able to fix this within a month or so now.

**Comment by Merancapeman** [comment] 2016-03-02 05:58
I'm pretty sure the problem is the size, here. I've encountered a similar error, and the only way I could get it to stop (after closing client, disabling mod, opening client, loading map, closing client, re-enable mod, re-open client) was by limiting the size of the gen-zone. Turns out the zone is ridiculously small (in my terms, anyway. I can't possibly have more than a 50 x 50 x 35 area). Is that normal?

**Closed** 2016-03-09 22:16 UTC

**Comment by Ivorforce** [comment] 2016-03-09 22:18
Your structure was spawning too low. Now it will spawn, although the problem that part of it might get cut off from spawning too low remains. I recommend keeping a look out for #45, which will allow you to specify this as a spawn condition ('enough space remaining to bedrock').
