### ISSUE TITLE
Excessive cascading worldgen lag

### ISSUE THREAD

**Issue by Keaft** [Ivorforce/RecurrentComplex#354] opened 2018-10-19 05:05 UTC
`Recurrent Complex loaded a new chunk [-214, -16] in dimension 0 (overworld) while populating chunk [-213, -16], causing cascading worldgen lag. (etc. etc. on and on quite a lot.)`

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

Edited: because everything I was thinking was wrong. It's all about adding an 8 block buffer to ensure that structures generate in the middle of loaded chunks and not spill over into other chunks. 

#350

**Comment by cyberpwnn** [comment] 2018-10-30 09:22
You could also just generate  a larger schematic in chunks as they are requested. Use structure files. Modulo is friend.

**Comment by Daenyth** [comment] 2018-11-12 17:40
I'm seeing this error also, it was stopped me from closing the game

**Comment by yanphi** [comment] 2019-01-10 23:39
I'm sorry, but did you manage to fix this/ how did you fix this? Thanks

**Comment by May-salkiriiss** [comment] 2019-02-11 16:42
how would i fix this then?

**Comment by Keaft** [comment] 2019-02-11 18:33
Just a friendly reminder to take a look at the link in my original post. I'm not the RecurrentComplex mod developer, but consider looking through that link and doing research with your own world/modpack to see how badly it actually effects you. 

This issue is more or less about getting the information out there for the mod developer and for you the player/modpack creator. 

Definitely recommend using Dynmap to figure out how bad the cascading actually is.

**Comment by Ivorforce** [comment] 2019-03-11 22:26
I know the issue, and structures are being aligned correctly. The issue is unfortunately more complex due to ReC's complex (heh) mechanics.

Anyway - Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

**Closed by Ivorforce** 2019-03-11 22:26 UTC
