### ISSUE TITLE
The longest crash log Ive ever seen (No clue what is going on here)

### ISSUE THREAD

**Issue by EchenCraft** [Ivorforce/RecurrentComplex#210] opened 2017-05-22 23:01 UTC
No clue what to make of this but its happened several times, multiple mods seem to be involved and I cant even figure out what went wrong.

https://pastebin.com/iyX2Jxy4

**Comment by Ivorforce** [comment] 2017-05-23 20:09
Should be duplicate of #204.

**Closed by Ivorforce** 2017-05-23 20:09 UTC
