### ISSUE TITLE
Kicking players regularly

### ISSUE THREAD

**Issue by fcpwiz** [Ivorforce/RecurrentComplex#335] opened 2018-06-27 05:21 UTC
Every 30 minutes or so, all players get kicked directly after this gets logged in the console.

```
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[17, 0, 15], dest=[17, 0, 14]}=Wall, MazePassage{source=[16, 0, 14], dest=[17, 0, 14]}=Wall, MazePassage{source=[18, 0, 14], dest=[17, 0, 14]}=Path, MazePassage{source=[17, 1, 14], dest=[17, 0, 14]}=Wall, MazePassage{source=[17, -1, 14], dest=[17, 0, 14]}=Wall]
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[17, 0, 12], dest=[16, 0, 12]}=Path, MazePassage{source=[16, -1, 12], dest=[16, 0, 12]}=Wall, MazePassage{source=[16, 1, 12], dest=[16, 0, 12]}=Wall]
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:02] [pool-48-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[18, 0, 15], dest=[18, 0, 16]}=Path, MazePassage{source=[17, 0, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, 0, 17], dest=[18, 0, 16]}=Wall, MazePassage{source=[19, 0, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, -1, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, 1, 16], dest=[18, 0, 16]}=Wall]
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[17, 0, 15], dest=[17, 0, 14]}=Wall, MazePassage{source=[16, 0, 14], dest=[17, 0, 14]}=Wall, MazePassage{source=[18, 0, 14], dest=[17, 0, 14]}=Path, MazePassage{source=[17, 1, 14], dest=[17, 0, 14]}=Wall, MazePassage{source=[17, -1, 14], dest=[17, 0, 14]}=Wall]
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[17, 0, 12], dest=[16, 0, 12]}=Path, MazePassage{source=[16, -1, 12], dest=[16, 0, 12]}=Wall, MazePassage{source=[16, 1, 12], dest=[16, 0, 12]}=Wall]
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Did not find fitting component for maze!
> [02:55:23] [pool-49-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePassage{source=[18, 0, 15], dest=[18, 0, 16]}=Path, MazePassage{source=[17, 0, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, 0, 17], dest=[18, 0, 16]}=Wall, MazePassage{source=[19, 0, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, -1, 16], dest=[18, 0, 16]}=Wall, MazePassage{source=[18, 1, 16], dest=[18, 0, 16]}=Wall]
> [02:55:23] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: ruthlesswarrior lost connection: Disconnected
> [02:55:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: - ruthlesswarrior left
> [02:55:23] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Phanta lost connection: Disconnected
> [02:55:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: - Phanta left
> [02:55:23] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Jacob_Feuerstein lost connection: Disconnected
> [02:55:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: - Jacob_Feuerstein left
> [02:55:23] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: AnonSaffy lost connection: Disconnected
> [02:55:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: - AnonSaffy left
> [02:55:23] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: MaxDistructo lost connection: Disconnected
> [02:55:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: - MaxDistructo left
```

and 

```
> [23:10:06] [Server thread/ERROR] [reccomplex]: Error preparing structure: StoneMazeBig, Cause: Maze generation timed out: StoneMaze
> [23:10:26] [Server thread/ERROR] [reccomplex]: Error preparing structure: StoneMazeBig, Cause: Maze generation timed out: StoneMaze
```

**Comment by Ivorforce** [comment] 2019-03-11 22:32
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.

You also appear to have a problem with maze solving, so turning down mazeTimeout in the config might help you as well.

**Closed by Ivorforce** 2019-03-11 22:32 UTC
