### ISSUE TITLE
Cascading worldgen lag in version 1.4.8.2

### ISSUE THREAD

**Issue by Zalnor** [Ivorforce/RecurrentComplex#473] opened 2021-09-06 06:38 UTC
The version 1.4.8.2 of Recurrent Complex mod linked bellow causes cascading worldgen lag, by itself it wouldn't be that bad but in any sizeable modpack it adds on quite a bit of cascading worldgen lag. I have also included a link explaing exactly what that is and how to go about fixing it. Example setting and offset or flags when structures are spawned partially in a chunk and when adjesent chunks load it reads it and finishes generating the structure.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

https://www.curseforge.com/minecraft/mc-mods/recurrent-complex/files/2689602

**Comment by MagmaBro123** [comment] 2022-01-04 17:40
Mod's been dead for 2 years. Doubt this'll ever be fixed..

**Comment by ToyB-Chan** [comment] 2023-01-07 21:52
Yeah the cascading worldgen lag is pretty bad on this one. It generated 44 chunks at once at my end.

**Comment by Ivorforce** [comment] 2024-08-06 10:12
Duplicate of #155. A fix is not expected, I'm sorry to say. I recommend decreasing the number of structures generated, which usually alleviates the issue.

**Closed by Ivorforce** 2024-08-06 10:12 UTC
